In [21]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
#Gradient Boosting model
# test classification dataset
from sklearn.datasets import make_classification
# evaluate gradient boosting algorithm for classification
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report
from sklearn.model_selection import KFold
df = pd.read_csv("/Users/madisonwhyte/Downloads/data_subset.csv")

In [3]:
df.head()

,Unnamed: 0,Sample,SampleName,AT1G22630,AT1G22620,AT1G22610,Tissue,Ecotype,Genotype,Treatment,Project,TotalReads,UniqueMappedRatio,ReleaseDate
0,17117,GSM3178804,urt1 rep1 dataset #2,0.00,0.00,0.0,seedlings,--,urt1,--,PRJNA475117,1039688,0.2002,10/8/2018
1,2820,GSM1507902,Te ctrl rep3,61.64,29.59,0.0,rosette leaf,Te,Te,control,PRJNA261430,24510726,0.8412,9/22/2014
2,16447,GSM2915887,BA_2,19.16,36.65,0.0,seedlings,Col-0,--,BA,PRJNA429126,21775880,0.9044,10/1/2018
3,12342,SRX2899193,Col0_margin_rep2,95.46,23.76,0.0,leaves,Col-0,Col-0,--,PRJNA389787,10077394,0.7901,12/6/2017
4,159,DRX099518,DRS050614,0.00,15.69,0.0,root,Col-0,wild type,Mock,PRJDB6370,3990947,0.9492,9/28/2017

In [23]:
#assign X and Y variables
X = df.iloc[:, 3:6].values
y = df.iloc[:, 6].values

#Define features
kf = KFold(n_splits=5,random_state=42,shuffle=True)
train_percent = 0.75
# create training and testing subsets
train = np.random.choice(a=[True, False], size=len(y), p=[train_percent, 1-train_percent])
test = np.invert(train)
for train_index,val_index in kf.split(X):
    X_train,X_test = X[train],X[test],
    y_train,y_test = y[train],y[test]

#Gradient booster parameters
gradient_booster.get_params()

{'ccp_alpha': 0.0,
 'criterion': 'friedman_mse',
 'init': None,
 'learning_rate': 0.1,
 'loss': 'deviance',
 'max_depth': 20,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_iter_no_change': None,
 'random_state': None,
 'subsample': 1.0,
 'tol': 0.0001,
 'validation_fraction': 0.1,
 'verbose': 0,
 'warm_start': False}

In [ ]:
#Model    
gradient_booster = GradientBoostingClassifier(learning_rate=0.1, max_depth=20, random_state=10)

In [24]:
#fit the model
gradient_booster.fit(X_train,y_train)
#Accuracy
print(classification_report(y_test,gradient_booster.predict(X_test)))

              precision    recall  f1-score   support

      leaves       0.54      0.54      0.54       310
        root       0.81      0.89      0.85        95
rosette leaf       0.21      0.17      0.19        75
   seedlings       0.49      0.55      0.52       279
 whole plant       0.19      0.07      0.10        43

    accuracy                           0.53       802
   macro avg       0.45      0.45      0.44       802
weighted avg       0.51      0.53      0.51       802

In [29]:
#Gradient boosting with cleaned data, file MapRateFiltered1000_75.csv
df = pd.read_csv("/Users/madisonwhyte/Downloads/MapRateFilteredQuarter_75.csv")

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [30]:
df2= df.drop(columns=['TotalReads', 'UniqueMappedRate', 'ReleaseDate'])
df2["Tissue"]=df2["Tissue"].apply(str)
df2.head()

,Sample,Project,SampleName,PMID,Genotype,Ecotype,Tissue,AT1G01010,AT1G01020,AT1G01030,...,ATMG01380,ATMG01390,ATMG01400,ATMG01410,ATMG09450,ATMG09730,ATMG09740,ATMG09950,ATMG09960,ATMG09980
0,SRX4553469,PRJNA486068,Col-AA-2,30872424,wild type,Col-0,shoot,26.545170,24.811101,14.550045,...,30.755991,32.463146,0.575822,0.297742,0.0,0.0,1.292454,0.000000,2.317865,0.000000
1,SRX1761550,PRJNA321559,Bur-0 2h EV rep2,27412712,/,Bur-0,leaves,26.166510,12.513347,1.203811,...,73.375137,118.603951,0.000000,0.963938,0.0,0.0,0.000000,0.000000,0.000000,0.000000
2,ERX1946876,PRJEB19974,Timepoint 8,28402429,/,Col-0,rosette leaf,9.676083,18.930814,2.808465,...,2.607932,9.879561,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000
3,GSM2570403,PRJNA382136,R45N-2,29769331,/,/,root,39.971878,32.318929,2.662752,...,96.416344,145.957153,1.912956,1.067393,0.0,0.0,12.646601,6.827559,2.678854,3.824113
4,GSM3408822,PRJNA494179,ABA_6h_poly(A)+,30498193,Wild type,Col-0,seedlings,10.103819,20.407515,3.792198,...,19.247196,85.602142,0.614105,0.149243,0.0,0.0,0.678074,0.000000,0.000000,0.000000

In [ ]:
#assign X and Y variables
X = df.iloc[:, 6:37343].values
y = df.iloc[:, 6].values

#Define features
kf = KFold(n_splits=5,random_state=42,shuffle=True)
train_percent = 0.75
# create training and testing subsets
train = np.random.choice(a=[True, False], size=len(y), p=[train_percent, 1-train_percent])
test = np.invert(train)
for train_index,val_index in kf.split(X):
    X_train,X_test = X[train],X[test],
    y_train,y_test = y[train],y[test]

#Model    
gradient_booster = GradientBoostingClassifier(learning_rate=0.1, max_depth=20)

In [ ]:
#fit the model
gradient_booster.fit(X_train,y_train)
#Accuracy
print(classification_report(y_test,gradient_booster.predict(X_test)))